service: import-service

frameworkVersion: '3'

custom:
  bucketName: fashionable-shop-uploaded

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1
  environment:
    SQS_URL:
      Ref: SQSQueue
    SNS_ARN:
      Ref: SNSTopic

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - arn:aws:s3:::${self:custom.bucketName}
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - arn:aws:s3:::${self:custom.bucketName}/*
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        Fn::GetAtt: [SQSQueue, Arn]
    - Effect: "Allow"
      Action: "sns:*"
      Resource:
        Ref: SNSTopic

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          method: get
          path: import
          cors: true
          authorizer:
            name: tokenAuthorizer
            arn: "arn:aws:lambda:eu-west-1:505793413497:function:authorization-service-dev-basicAuthorizer"
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: fashionable-shop-uploaded
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
          existing: true
  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt: [SQSQueue, Arn]

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: shinkarenko.max97@gmail.com
        Protocol: email
        TopicArn:
          Ref: SNSTopic