service: product-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          method: get
          path: products
          cors: true
  getProductsById:
    handler: handler.getProductsById
    events:
      - http:
          method: get
          path: products/{id}
          cors: true
          request:
            parameters:
              paths:
                id: true
